### ISSUE TITLE
finetune k折训练时 cuda out of memory

### ISSUE THREAD

**Issue by Wchoward** [dbiir/UER-py#167]
在运行finetune/run_classifier_cv.py时，每运行到下一个fold时显存增加，直到CUDA out of memroy

**Comment by P01son6415** [comment]
我们更新了代码，请再试一下是否还有这个问题

**Comment by Wchoward** [comment]
> 我们更新了代码，请再试一下是否还有这个问题

您好，我解决了OOM的问题，看了下您的代码，仅使用`torch.cuda.empty_cache()`在我之前的尝试中是无法解决的。
我通过 `import gc` ，并在每个fold结束前（eval后）
```
del model, scheduler, optimizer
gc.collect()
torch.cuda.empty_cache()
```
解决了OOM问题。
但是不知道这样写是否合理？还希望您能帮忙看一下，谢谢！

**Comment by P01son6415** [comment]
这个问题在我们这边的环境并没有出现，可能是版本的问题，您的torch和python版本是？

**Comment by Wchoward** [comment]
python 3.6.10
torch 1.2.0
cudatoolkit 10.0.130
cudnn 7.6.5

**Comment by P01son6415** [comment]
可能是torch版本的原因，我们用的是1.8。
后续用低版本看看能不能复现这个问题，将您的方案合并进去，感谢您的反馈！

**Comment by P01son6415** [comment]
您也可以将您的方案提一个pull request，我们一起来讨论一下如何改进现有的代码

**Comment by P01son6415** [comment]
如果您还有此类问题可以重启这个issue
