### ISSUE TITLE
A100 多卡训练，出现问题，程序一直卡死，A100 Multi GPU triaining has some problem

### ISSUE THREAD

**Issue by supinyu** [dbiir/UER-py#280]
1、背景
使用4张卡的A100训练robert模型，单卡可以训练，多卡一直卡死，并且**GPU利用率一直100%不发生变化，每张卡显存战用1.3G左右**

Using A100 training Robert model with 4 GPU, single GPU can be trained, multiple GPU are stuck all the time, and the GPU utilization rate remains 100% unchanged. The GPU memory of each is about 1.3g

2、问题
数据预处理  
data preprocess
python3 preprocess.py --corpus_path corpora/CLUECorpusSmall_5000_lines.txt \
                          --vocab_path models/google_zh_vocab.txt \
                          --dataset_path pt_data/CLUECorpusSmall_5000_robert_seq128_dataset.pt \
                          --processes_num 5 \
                          --seq_length 128  \
                          --docs_buffer_size  1000000 \
                          --dynamic_masking  --data_processor mlm
预处理文件没有问题，之后使用多卡进行训练的时候，出现问题
多卡命令 
muli gpu  command
python3 pretrain.py --dataset_path pt_data/CLUECorpusSmall_5000_robert_seq128_dataset.pt  \
                    --vocab_path models/google_zh_vocab.txt \
                    --config_path models/bert/medium_config.json \
                    --output_model_path models/CLUECorpusSmall_5000_roberta_medium_seq128_model.bin \
                    --world_size 4 --gpu_ranks 0 1 2 3  \
                    --total_steps 1000000 --save_checkpoint_steps 100000 --report_steps 50000 \
                    --learning_rate 1e-4 --batch_size 64 \
                    --data_processor mlm --target mlm
出现的情况如下，GPU的利用率一直维持在100%，并且不发生变化，每张卡显存占用1.3G左右

如果是单卡进行训练，则没有问题，单卡命令如下
If it is a single GPU training, there is no problem. The single GPU command is as follows
python3 pretrain.py --dataset_path pt_data/CLUECorpusSmall_5000_robert_seq128_dataset.pt  \
                    --vocab_path models/google_zh_vocab.txt \
                    --config_path models/bert/medium_config.json \
                    --output_model_path models/CLUECorpusSmall_5000_roberta_medium_seq128_model.bin \
                    --world_size 1 --gpu_ranks 0  \
                    --total_steps 1000000 --save_checkpoint_steps 100000 --report_steps 50000 \
                    --learning_rate 1e-4 --batch_size 64 \
                    --data_processor mlm --target mlm
此时显存占用也是正常的，大概9个G左右
At this time, the GPU memory is also normal, about 9 G

torch version 1.7.1 
代码版本，就是目前最新的master的代码

请问能不能帮忙看一下是什么问题

**Comment by hhou435** [comment]
您好，我这边按您给的命令是可以正常训练的，我看您用的report_steps是50000，可以尝试用小一些的，看看能否打印出log，判断一下是卡死还是没有训练完

**Comment by supinyu** [comment]
hello，我这边减少了report_steps
单卡的效果如下：
<img width="1429" alt="截屏2022-03-02 20 06 03" src="https://user-images.githubusercontent.com/12369067/156368856-31cbee15-782c-4c18-8804-5b6dea71a435.png">

多卡的效果如下
<img width="1433" alt="截屏2022-03-02 21 15 47" src="https://user-images.githubusercontent.com/12369067/156369042-a5149d4a-523c-4671-bf2e-c15f517e0336.png">

GPU利用率
<img width="891" alt="截屏2022-03-02 20 01 15" src="https://user-images.githubusercontent.com/12369067/156369075-858b2006-bafa-4864-bbcb-c6f55322a1dd.png">

监控
![截屏2022-03-02 20 02 23](https://user-images.githubusercontent.com/12369067/156369114-741a2d6b-a5e7-4f14-b358-57eac125407d.png)

多卡的时候，感觉还是卡死了，一直也没有出report

**Comment by Cappuccino-Sugar** [comment]
请问您的问题解决了吗
![image](https://github.com/dbiir/UER-py/assets/61620218/2f6d341c-c048-4336-a89d-26c00c9001a9)

**Comment by supinyu** [comment]
可能是我这边环境的问题，我这边在看一下

**Comment by yanghan-shanda** [comment]
我也遇到同样的问题了，两年过去了，请问问题解决了吗
